apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: react-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-react-app
          image: react:v1
          ports:
            - containerPort: 3000
